### PR TITLE
[Kiln v2] Fix claim function signature

### PR DESCRIPTION
**Pull request by pwnh4**
Claim function of the exit queue changed from `claim(uint32[],uint32[],uint16)` to `claim(uint256[],uint32[],uint16)` and `multiClaim(address[],uint32[][],uint32[][])` to `multiClaim(address[],uint256[][],uint32[][])`, here is a PR to take this change into account (especially regarding the function selector).

### CODE REVIEW

**Review by Jorgecmartins — APPROVED** [review]

**Review by jmartins-ledger — DISMISSED** [review]

**Comment by cedelavergne-ledger** [comment]
Hello,
1 check is fail, and expected workflows for Ledger guidelines_enforcer are not implemented

Can you please check on your side?

**Comment by pwnh4** [comment]
> Hello, 1 check is fail, and expected workflows for Ledger guidelines_enforcer are not implemented
> 
> Can you please check on your side?

Hey, I am using the latest version of zemu in CI and tests dependencies, any idea why tests still timeout?

**Comment by agrojean-ledger** [comment]
> > Hello, 1 check is fail, and expected workflows for Ledger guidelines_enforcer are not implemented
> > Can you please check on your side?
> 
> Hey, I am using the latest version of zemu in CI and tests dependencies, any idea why tests still timeout?

@loicttn you need to change the name of plugin elf that should be loaded in `test.fixture.js` you have `kiln` instead of `Kiln` and the CI fails with `Invalid lib name in /project/app/bin/plugin_nanox.elf (Kiln vs kiln)`

**Comment by agrojean-ledger** [comment]
@loicttn I have tried with `Kiln` instead of `kiln` and the tests run but still fail...
You should configure the ethereum app it seems, before running your tests : 

`EthAppPleaseEnableContractData: Please enable Blind signing or Contract data in the Ethereum app Settings`

You need something like that in your `function zemu(device, func) {` of `test.fixture.js` , **before loading the plugin** : 

```           
           if (dev.name == "stax") {
                const settingNav = new TouchNavigation([
                ButtonKind.InfoButton,
                ButtonKind.NavRightButton,
                ButtonKind.ToggleSettingButton1,
                ]);
                await sim.navigate(".", `${dev.prefix.toLowerCase()}-setting`, settingNav.schedule, true, false);
            } else {
                await sim.clickRight();
                await sim.clickBoth(undefined, false);
                await sim.clickBoth(undefined, false);
            }
```

**Comment by pwnh4** [comment]
> @loicttn I have tried with `Kiln` instead of `kiln` and the tests run but still fail... You should configure the ethereum app it seems, before running your tests :
> 
> `EthAppPleaseEnableContractData: Please enable Blind signing or Contract data in the Ethereum app Settings`
> 
> You need something like that in your `function zemu(device, func) {` of `test.fixture.js` , **before loading the plugin** :
> 
> ```
>            if (dev.name == "stax") {
>                 const settingNav = new TouchNavigation([
>                 ButtonKind.InfoButton,
>                 ButtonKind.NavRightButton,
>                 ButtonKind.ToggleSettingButton1,
>                 ]);
>                 await sim.navigate(".", `${dev.prefix.toLowerCase()}-setting`, settingNav.schedule, true, false);
>             } else {
>                 await sim.clickRight();
>                 await sim.clickBoth(undefined, false);
>                 await sim.clickBoth(undefined, false);
>             }
> ```

So it seems that the claim function is not recognized now that we updated its signature 🤔 , if I understand correcly your solution is meant to enable blind signing which we want to avoid here, investigating why the claim selector is not recognized

**Comment by agrojean-ledger** [comment]
> So it seems that the claim function is not recognized now that we updated its signature 🤔 , if I understand correcly your solution is meant to enable blind signing which we want to avoid here, investigating why the claim selector is not recognized

If you don't intend to use bling signing, don't use the solution I suggested.

**Comment by agrojean-ledger** [comment]
@loicttn you need to fix the app database : 

```
Error:  Missing 'appFlags' for 'stax'
Checking manifest_nanosp.json
Checking for target 'nanos2' and variant 'kiln'
Retrieved listapploadparams:
```
As per the CI tip : `Creating a PR on https://github.com/LedgerHQ/ledger-app-database to update the app-params-database.json`

Then put me or someone else from our team and we'll merge the fix

**Comment by cedelavergne-ledger** [comment]
Hello,

Currently, we accept errors in the workflow `guidelines_enforcer`, mainly because we still have pending work for the plugin case.
As soon as the **E2E** tests are ok, I will merge and start the deployment.
Just tell me when it is ok for the **E2E** tests (seems you only validate NANOS and NANOX. Is it sufficient?)

**Comment by pwnh4** [comment]
> Hello,
> 
> Currently, we accept errors in the workflow `guidelines_enforcer`, mainly because we still have pending work for the plugin case. As soon as the **E2E** tests are ok, I will merge and start the deployment. Just tell me when it is ok for the **E2E** tests (seems you only validate NANOS and NANOX. Is it sufficient?)

E2E tests are all passing, so ok to merge thanks a lot 👍

**Pull request merged**
